### ISSUE TITLE
move_base not working in simulator

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#122]
The move_base node is complaining that it's not receiving one of the point clouds that rtabmap should be publishing.

move_base is producing warnings like this:
```
The /planner_cloud observation buffer has not been updated for 192.68 seconds, and it should be updated every 2.00 seconds.
```

There is a remap in `nav.launch`:
```
    <remap from="/planner_cloud" to="/rtabmap/cloud_obstacles"/>
```

This remap means that move_base is actually subscribed to a topic called `rtabmap/cloud_obstacles`.

I did `rostopic echo /rtabmap/cloud_obstacles` and it looks like this topic is being published but it appears to not be published frequently.

I'm not sure if this is an error with the way launch files and topics are set up or this is a matter of rtabmap not producing the cloud_obstacles map fast enough.

**Comment by mdepp** [comment]
This is fixed (but still buggy)
