### ISSUE TITLE
Diff drive controller isn't working

### ISSUE THREAD

**Issue by davidlenfesty** [UofA-SPEAR/software#15]
We can interface with the rover hardware through the rover controller (which is implemented debatably correctly).

Diff drive controller isn't working correctly yet though. The problem - I believe - stems from the importing of URDF.

When you run the diffdrive.launch file from spear_simulator it works, while running an equivalent launch file in spear_rover does not. They pull from the same URDF file. I think the big issue is that it's trying to connect to/load controllers that don't exist, and it just kind of panics or something.

The likely solution is to modify the rover URDF file so it matches with the CASE_hardware_interface, or to modify the CASE_hardware_interface to fit with the URDF, or a bit of both until we have a "proper" description and controller.

**Comment by jo12bar** [comment]
Might have fixed it...? Check out commit 884a36c20c963738c44aef2b47173f7e953707a5. I'll test it more extensively on Saturday, but the controller doesn't crash anymore. Looks like it was actually a threading issue, not a URDF issue. Also, Travis has broken again, but it seems to be from linting errors that got fixed in master. I'll pull in changes probably sometime later today or tomorrow.

**Comment by davidlenfesty** [comment]
No more diff drive controller. I rewrote a thing to manage the wheels, and ros_control is not necessary for us at all.

**Comment by jo12bar** [comment]
Yay!

@davidlenfesty: Since I've been out of the loop for a while, what's this new thing?

**Comment by davidlenfesty** [comment]
We looked at the code for the ros diff_drive_controller and realised it wasn't doing anything fancy. So we wrote seperate odometry and skidsteer nodes using some slightly-better-than-assuming-its-two-wheels kinematics I thought up.

[This node](https://github.com/UofA-SPEAR/software/blob/master/spear_rover/src/odom_tf_publisher.cpp) publishes tf frames from the wheel odometry data, and [this node](https://github.com/UofA-SPEAR/software/blob/master/spear_rover/src/twist_to_skidsteer.cpp) handles generating wheel commands.

(Note that these nodes as is don't work, we need to push code from the TX2)
