### ISSUE TITLE
Upgrade to ROS Noetic

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#200]
ROS Noetic has been released. Migrating will allow us to use python 3.

There is a migration guide here: http://wiki.ros.org/noetic/Migration

One way to go about this would be to just change our dockerfile to install noetic and ubuntu 20.04 and fix whatever breaks. If some of the ROS packages we use can't be installed with `apt-get` we will have to make the dockerfile or unpack script manually clone those repose and build.

**Comment by mdepp** [comment]
I have a branch for this: https://github.com/UofA-SPEAR/software/tree/rain/noetic

But I had to remove canros to make it work... not sure how the CAN stuff will work in noetic / python 3.

**Comment by davidlenfesty** [comment]
> But I had to remove canros to make it work... not sure how the CAN stuff will work in noetic / python 3.

Better, the answer is better. With python 3 we can migrate mapper.py to pyuavcan, or if we want to keep w/ the new C++ node for performance/latency reasons it'll be exactly the same.

**Comment by mdepp** [comment]
Mostly done per #282. The rest is covered by #284.
