### ISSUE TITLE
GPS, IMU, spectrometer, camera displays

### ISSUE THREAD

**Issue by mdepp** [UofA-SPEAR/software#224]
The IMU isn't very important for manual controls, but if we had it we could gather data to improve our localization algorithms later.

**Comment by rpshukla** [comment]
The currently plan to display sensor data is to use this gui: https://github.com/UofA-SPEAR/spearMCT/

I'm currently sorting out this issue: https://github.com/UofA-SPEAR/spearMCT/issues/3

**Comment by mdepp** [comment]
Camera displays good enough for now, GPS can theoretically be displayed in rover-map-view. IMU is autonomy-related and is on hold.
