### ISSUE TITLE
Stream compressed camera feed to the base station

### ISSUE THREAD

**Issue by mdepp** [UofA-SPEAR/software#228]
Look at Johann's wokr with h264

**Comment by rpshukla** [comment]
Found the Johann's PRs in the old repos:
https://github.com/UofA-SPEAR/rover2/pull/6
https://github.com/UofA-SPEAR/station2/pull/10

**Comment by mdepp** [comment]
Already done with nimbro_network and image downsampling. Tested during competition and it works well.
