### ISSUE TITLE
Create SMACH state to search for ARUCO marker

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#264]
https://circ.cstag.ca/2021/rules/#autonomy-guidelines

Some tasks will require to rover to navigate to an aruco tag. This tag may not be immediately visible to the rover if the rover is not close enough or is facing the wrong direction. We should have a SMACH state where the rover searches the nearby area until it recognizes an aruco tag in its camera feed.

**Comment by mdepp** [comment]
Closing all autonomy-related issues
