### ISSUE TITLE
Document dependencies

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#28]
We should move all the build and runtime  dependencies into one script. Currently, the dockerfile only has build time dependencies.

**Comment by rpshukla** [comment]
To run the simulator, you need:
* `ros-kinetic-rtabmap-ros`
* `ros-kinetic-controller-manager`

And possibly others.

**Comment by davidlenfesty** [comment]
Why aren't we using rosdep? I just realised this. there's literally a rosdep command that will run all the dependencies, we just need to make sure the dependencies are in the package.xml file

**Comment by davidlenfesty** [comment]
I added an alias for this in pull request #44

**Comment by mdepp** [comment]
Dependencies are much better now, especially since we are using docker
