### ISSUE TITLE
CI python linting always fails due to knob.py

### ISSUE THREAD

**Issue by mdepp** [UofA-SPEAR/software#36]
It's in master and is making this test fail for *every* new branch. Does anyone know why this file is here anyway? As far as I can tell nothing uses it. The closest is in `arm.py` which has 

```python
from kivy.garden.knob import Knob
```
which is probably not actually importing `knob.py` unless someone messed around with `__init__.py` or something.

**Comment by davidlenfesty** [comment]
Yeah it looks like it may have been imported because of versioning issues or to use as a reference when writing other code. Fixed in commit 05e139fbc3c160962f026022ba75dc1b137ed652
