### ISSUE TITLE
XML style guide

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#86]
We currently have no imposed style guide for xml. Since all of our launch files and .urdf models are in xml, we should have a consistent style.

We need to:
1. Pick a commonly-used style guide for xml (preferably with 2 space indentation since this is what we are mostly using currently)
2. Integrate xml linting in the travis build so that the build fails when there are style violations.

**Comment by mdepp** [comment]
Couldn't find a commonly-used style guide per se, but got linting working using xmllint --format.
