### ISSUE TITLE
Figure out docker networking

### ISSUE THREAD

**Issue by rpshukla** [UofA-SPEAR/software#87]
We would like to run ROS inside a docker container on both the base station computer and the rover computer. To do this, we need to be able to manually assign a static ip to both docker containers. Also, each docker container needs to be able to connect to the host computer's network.

We'll need to figure out how to configure networking in docker and write instructions on how to set it up on one's own computer.

These instructions should go in the main README.

**Comment by jo12bar** [comment]
Would we want the Docker daemon running on the base station, the rover, or both? 

Disjointed, random brain dump ahead. Sorry 😅

Some things that I do know:

- When running locally, the docker CLI calls an API exposed on a Unix socket that the daemon creates.
- The [docker daemon docs](https://docs.docker.com/v17.09/engine/reference/commandline/dockers) mention that the possible socket types are unix, tcp, and fd:
  - unix is the default, and only works locally (it’s basically a sort of IPC socket). It gets created at /var/run/docker.sock.
  - tcp supports remote control, but we’ve had issues with tcp, latency, and range before.
  - fd is a Systemd socket activation thing. Not useful to us.
  - I don’t think there’s a udp socket option 😕

I'd have to do more research on this to really know what I'm talking about though...

I think we could get away with running the daemon on both rover and base station. There might be some sort of pre-made distributed docker daemon thing, as it's a pretty common thing in huge data centers. Finding one that works with UDP could be a challenge.

We could just have the docker containers on the rover and the base station expose specific ports, and communicate with {base station or rover IP}:{exposed port of container}. And then we could set the daemon on the rover to use a TCP socket, so we can remotely start/stop containers or ssh into them from the base station. But we should avoid TCP for any actually critical, run-time tasks.

I dunno. I'll try to look at this more later.

**Comment by Petelliott** [comment]
docker would only be used for development and testing, or maybe on the station.

the docker demon scoket is only for starting/stoping and controlling the containers, otherwise it's just regular networking.

the meaning of 'docker networking' in this post is creating virtual linux interfaces, so that when someone runs the station and the rover on the same computer, the software believes it is connected to a certain ip address/hostname, when it is not.

**Comment by Petelliott** [comment]
oops, I misread the issue. on the actual rover and server, we would configure the ips/ports to those of the actual host system

**Comment by jo12bar** [comment]
Ah, I see. Sorry, didn't understand the context well enough. 🙂

That should be relatively simple during development though. There's a [CLI interface (`docker network ...`)](https://docs.docker.com/engine/reference/commandline/network/) for creating local inter-container networks. I think we can even have their ports seperate from the system's, so the only development difference when it comes to networking is running a couple of commands to create two instances of the container attached to the network.

Maybe we could even use a [Docker compose file](https://docs.docker.com/compose/) for local dev? Then setting up the containers would just be a single `docker compose up`.

**Comment by Petelliott** [comment]
docker compose was always the plan.

ports are a transport layer construct that is irrelevant to docker networking. basically you can put docker containers on a virtual lan together + provide dns to resolve their hostnames.

As I understand it all of our software is configured by hostname, so we shouldn't need to give the containers ip addresses.

**Comment by mdepp** [comment]
I think using network=host solves this
